# Generated by Django 5.1.3 on 2024-11-30 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=125)),
                ('response', models.CharField(max_length=10000)),
                ('created', models.DateField(auto_now=True)),
                ('user_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='aichat.userdata')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
