# Generated by Django 5.1.3 on 2024-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0002_alter_chatdata_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='prompt',
            field=models.CharField(default='', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='response',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
    ]
