# Generated by Django 5.1.3 on 2024-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0003_alter_chatdata_prompt_alter_chatdata_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
