# Generated by Django 5.1.3 on 2024-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0004_alter_chatdata_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
