# Generated by Django 5.1.3 on 2024-12-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0005_alter_chatdata_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatdata',
            options={},
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
