# Generated by Django 5.1.3 on 2024-12-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0007_alter_chatdata_options_alter_chatdata_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatdata',
            options={'ordering': ['-created']},
        ),
    ]
