# Generated by Django 5.1.3 on 2024-12-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0008_alter_chatdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatdata',
            options={},
        ),
    ]
